# Generated by Marten 0.5.7 on 2025-08-02 11:18:50 +02:00

class Migration::Auth::V202508021118501 < Marten::Migration
  def plan
    create_table :auth_user do
      column :id, :big_int, primary_key: true, auto: true
      column :email, :string, max_size: 254, unique: true
      column :password, :string, max_size: 128
      column :created_at, :date_time
      column :updated_at, :date_time
    end
  end
end
