# Generated by Marten 0.5.7 on 2025-08-02 13:29:12 +02:00

class Migration::Main::V202508021329121 < Marten::Migration
  depends_on :main, "202508021118501_create_main_article_table"

  def plan
    add_column :main_article, :quelle, :string, max_size: 255
  end
end
