# Generated by Marten 0.5.7 on 2025-08-02 11:18:50 +02:00

class Migration::Main::V202508021118501 < Marten::Migration
  def plan
    create_table :main_article do
      column :created_at, :date_time
      column :updated_at, :date_time
      column :id, :big_int, primary_key: true, auto: true
      column :title, :string, max_size: 255
      column :content, :text
    end
  end
end
