# Generated by Marten 0.5.7 on 2025-08-02 13:45:01 +02:00

class Migration::Main::V202508021345011 < Marten::Migration
  depends_on :main, "202508021329121_add_quelle_to_main_article_table"

  def plan
    change_column :main_article, :quelle, :string, max_size: 255
  end
end
